# Generated by Django 4.1.7 on 2023-04-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(max_length=50)),
                ('song_name', models.CharField(max_length=100)),
                ('song_url', models.CharField(max_length=10)),
                ('song_image', models.CharField(max_length=50)),
                ('artist_name', models.CharField(max_length=50)),
                ('popularity', models.IntegerField()),
                ('duration', models.FloatField()),
                ('song_type', models.CharField(max_length=50)),
            ],
        ),
    ]
