# Generated by Django 4.1.7 on 2023-04-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0002_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='song_url',
            field=models.CharField(max_length=100),
        ),
    ]
