# Generated by Django 4.1.7 on 2023-04-18 07:22

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0003_alter_songs_song_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='artist_name',
        ),
        migrations.AddField(
            model_name='songs',
            name='artists_name',
            field=django_mysql.models.ListCharField(models.CharField(max_length=50), default=['kapil', 'prashant'], max_length=510, size=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='songs',
            name='song_image',
            field=models.CharField(max_length=100),
        ),
    ]
