# Generated by Django 4.1.7 on 2023-04-21 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0005_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='email',
        ),
    ]
