# Generated by Django 4.1.7 on 2023-04-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0006_rename_username_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='artists_name',
            field=models.CharField(max_length=100),
        ),
    ]
