# Generated by Django 4.1.7 on 2023-04-24 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0007_alter_songs_artists_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Songs',
        ),
    ]
