# Generated by Django 4.1.7 on 2023-04-24 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0009_songs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Musician',
        ),
        migrations.DeleteModel(
            name='Songs',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
