# Generated by Django 4.1.7 on 2023-04-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0011_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mp3Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=50)),
                ('track_mp3', models.BinaryField(max_length=2147483647)),
            ],
        ),
    ]
