# Generated by Django 4.1.7 on 2023-05-02 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0014_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='likes',
        ),
    ]
