# Generated by Django 4.1.7 on 2023-05-03 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('temp', '0015_remove_profile_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('elapsed_time', models.PositiveIntegerField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temp.songs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
